version: 2

models:
  - name: places
    description: This table has basic information about demographic

    columns:
      - name: place_id
        description: This is a unique identifier for place
        tests:
          - unique
          - not_null
      - name: city
        description: City name
        tests:
          - not_null
      - name: County
        description: County name
        tests:
          - not_null
      - name: country
        description: Country name
        tests:
          - not_null
